[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spert"
version = "0.1"
dependencies = [
    "numpy",
    "iapws",
    "salome-c3po==2.1.1",
]
